bin/install-protoc-apt.sh
bin/install-protoc-osx.sh

The location for the install of protobuf was missing v within the version part of the url.
Have amended in both installation scripts

Amended protobuf install location

---

cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/CloudFoundryClient.java
cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/CloudFoundryOperations.java
cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/domain/CloudUser.java
cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/rest/CloudControllerClient.java
cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/rest/CloudControllerClientImpl.java
cloudfoundry-client-lib/src/test/java/org/cloudfoundry/client/lib/CloudFoundryClientTest.java

Hello Scott
As space creation does not handle user role, it has to be done after. So once a space is created, current logged user can be assign to it. Assigned user roles are identical to CF CLI ones, ie Manager, Developer
and Auditor.
Only assign and list are implemented.
Related to PR #238

Add space user role assignation for current user.

---

cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/CloudCredentials.java
cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/oauth2/OauthClient.java

OAuth2 tokens obtain via implicit OAuth 2.0 authentication can not be refreshed,
and since there is no username / password passed in to the cloud credentials we
just need to use the provided token without trying to refresh.
Resolves issue https://github.com/cloudfoundry/cf-java-client/issues/214

Allow users to specify weather a token is refreshable or not

---

cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/util/CloudEntityResourceMapper.java

Sometime between PCF 1.3 and CF-202 the events api endpoint changed from returning UTC formatted timestamps to UTC zulu formatted timestamps.  This is a fix to make date parser work with either format.

Fix date parser for UTC Z dates

---

cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/CloudFoundryClient.java
cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/CloudFoundryOperations.java
cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/domain/CloudUser.java
cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/rest/CloudControllerClient.java
cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/rest/CloudControllerClientImpl.java
cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/util/CloudEntityResourceMapper.java
cloudfoundry-client-lib/src/test/java/org/cloudfoundry/client/lib/CloudFoundryClientTest.java

Add userdGuid to  associatexxxxWithSpace method, if null, use current user.
Fix associatexxxxWithSpace orgName param used to search for space: if null use current org, else use orgName.
Add getOrganizationUsers to be able to retrieve all users of an organization indexed by username.
Change associatexxxxWithSpace method signatures introduced with #271 - getSpaceDevelopers(String spaceName) returns NPE in version 1.1.1
This closes #278 - As CLI does, add any user to a space.

Associate any organization user to a space.

---

cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/uaa/clients/ReactorClients.java
cloudfoundry-client-reactor/src/test/java/org/cloudfoundry/reactor/uaa/clients/ReactorClientsTest.java
cloudfoundry-client-reactor/src/test/resources/fixtures/uaa/clients/PUT_{id}_meta_request.json
cloudfoundry-client-reactor/src/test/resources/fixtures/uaa/clients/PUT_{id}_meta_response.json
cloudfoundry-client/src/main/java/org/cloudfoundry/uaa/clients/Clients.java
cloudfoundry-client/src/main/java/org/cloudfoundry/uaa/clients/_UpdateMetadataRequest.java
cloudfoundry-client/src/main/java/org/cloudfoundry/uaa/clients/_UpdateMetadataResponse.java
cloudfoundry-client/src/test/java/org/cloudfoundry/uaa/clients/UpdateMetadataRequestTest.java

This change adds the api to update client metadata (`PUT /oauth/clients/:id/meta`)

Update Client Metadata

---

cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/uaa/clients/ReactorClients.java
cloudfoundry-client-reactor/src/test/java/org/cloudfoundry/reactor/uaa/clients/ReactorClientsTest.java
cloudfoundry-client-reactor/src/test/resources/fixtures/uaa/clients/GET_{id}_meta_response.json
cloudfoundry-client/src/main/java/org/cloudfoundry/uaa/clients/Clients.java
cloudfoundry-client/src/main/java/org/cloudfoundry/uaa/clients/_GetMetadataRequest.java
cloudfoundry-client/src/main/java/org/cloudfoundry/uaa/clients/_GetMetadataResponse.java
cloudfoundry-client/src/test/java/org/cloudfoundry/uaa/clients/GetMetadataRequestTest.java

This change brings the api to retrieve metadata (`GET /oauth/clients/:id/meta`)

Get Client Metadata

---

cloudfoundry-client-reactor/src/test/java/org/cloudfoundry/reactor/client/AbstractClientApiTest.java
cloudfoundry-client-reactor/src/test/java/org/cloudfoundry/reactor/client/v2/applications/ReactorApplicationsV2Test.java
cloudfoundry-client-reactor/src/test/java/org/cloudfoundry/reactor/client/v3/packages/ReactorPackagesTest.java
cloudfoundry-util/src/main/java/org/cloudfoundry/util/OperationUtils.java
integration-test/src/test/java/org/cloudfoundry/AbstractIntegrationTest.java
integration-test/src/test/java/org/cloudfoundry/client/v2/ApplicationsTest.java

Mono<byte[]> collectByteArray(Flux<byte[]> bytes) is pulled out to a static
method in ResourceUtils so that it is available to the four places it is used
(twice in integration tests and twice in Reactor unit tests). This actually
increases the runtime jar (util is available in production) but not the
runtime footprint. It is a reasonably useful method, however, and reduces the
interdependencies in the test code.

Polishing: replace duplicate code by util static function

---

cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/client/QueryBuilder.java
cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/client/v2/FilterBuilder.java
cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/client/v3/FilterBuilder.java
cloudfoundry-client-reactor/src/test/java/org/cloudfoundry/reactor/client/QueryBuilderTest.java
cloudfoundry-client-reactor/src/test/java/org/cloudfoundry/reactor/client/v2/FilterBuilderTest.java
cloudfoundry-client-reactor/src/test/java/org/cloudfoundry/reactor/client/v3/FilterBuilderTest.java

Hello,
The cf command-line client supports mapping of empty hosts.
For instance (getting an empty host for domain, one result): /v2/routes?inline-relations-depth=1&q=host%3A%3Bdomain_guid%3A6906bee2-0115-47f6-b7d1-3ef1e455e8e1
"%3A%3B" -> ":;"
The v3 client does not support this feature. Empty parameters are skiped and not set as parameters in the request url.
The following problem occurrs. You have two hosts mapped to domain and application.
When you try to get this empty host all of the hosts for this domain are returned.
Example:
ListSpaceRoutesRequest.Builder requestBuilder = ListSpaceRoutesRequest.builder();
requestBuilder.host("");   -> Ignored in the request (all host are returned)
This pull request removes the checks for empty parameters and allows using empty parametrs.
Could you …

Allow empty query parameters

---

cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/uaa/UsernameProvider.java

Currently, the `UaaSigningKeyResolver` must use `.block()` in order to implement a blocking interface.  Use of this API within a non-blocking thread is illegal since Reactor 3.2.  A `.scheduleOn()` call, moving the execution to an elastic
scheduler was in place but turned out to be the wrong implementation.  This change updates the protection to a `.publishOn() `to move it out of a non-blocking thread at the right time.

Protect Blocking API

---

cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/client/_ReactorCloudFoundryClient.java
cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/client/v3/stacks/ReactorStacksV3.java
cloudfoundry-client-reactor/src/test/java/org/cloudfoundry/reactor/client/v3/stacks/ReactorStacksV3Test.java
cloudfoundry-client-reactor/src/test/resources/fixtures/client/v3/stacks/GET_response.json
cloudfoundry-client-reactor/src/test/resources/fixtures/client/v3/stacks/GET_{id}_response.json
cloudfoundry-client-reactor/src/test/resources/fixtures/client/v3/stacks/PATCH_{id}_request.json
cloudfoundry-client-reactor/src/test/resources/fixtures/client/v3/stacks/PATCH_{id}_response.json
cloudfoundry-client-reactor/src/test/resources/fixtures/client/v3/stacks/POST_request.json
cloudfoundry-client-reactor/src/test/resources/fixtures/client/v3/stacks/POST_response.json
cloudfoundry-client/src/main/java/org/cloudfoundry/client/CloudFoundryClient.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/stacks/Stack.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/stacks/StacksV3.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/stacks/_CreateStackRequest.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/stacks/_CreateStackResponse.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/stacks/_DeleteStackRequest.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/stacks/_GetStackRequest.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/stacks/_GetStackResponse.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/stacks/_ListStacksRequest.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/stacks/_ListStacksResponse.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/stacks/_StackResource.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/stacks/_UpdateStackRequest.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/stacks/_UpdateStackResponse.java
cloudfoundry-client/src/test/java/org/cloudfoundry/client/v3/stacks/CreateStackRequestTest.java
cloudfoundry-client/src/test/java/org/cloudfoundry/client/v3/stacks/DeleteStackRequestTest.java
cloudfoundry-client/src/test/java/org/cloudfoundry/client/v3/stacks/GetStackRequestTest.java
integration-test/src/test/java/org/cloudfoundry/client/v3/StacksTest.java

Add support for V3 Stacks

---

cloudfoundry-client/src/test/java/org/cloudfoundry/client/v3/applications/GetApplicationProcessStatisticsRequestTest.java

This resolves a WARNING under Java 11 that was causing the pipline to break.

Use Double.valueOf instead of new Double.

---

cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/DefaultApplications.java
cloudfoundry-operations/src/test/java/org/cloudfoundry/operations/applications/DefaultApplicationsTest.java

avoid NPE, if environmentJsons is null from application entity

Avoid NPE in DefaultApplications.java

---

cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/util/Operator.java

Changes comparison type from == to .equals when checking if the response is 'unauthorised'/401

Fix for comparison of unauthorised check

---

cloudfoundry-client-reactor/src/test/java/org/cloudfoundry/reactor/client/v3/processes/ReactorProcessesTest.java
cloudfoundry-client-reactor/src/test/resources/fixtures/client/v3/processes/GET_{id}_stats_with_null_fields_response.json
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/processes/_ProcessStatisticsResource.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/processes/_ProcessUsage.java

Fixes https://github.com/cloudfoundry/cf-java-client/issues/1133
Additionally I find out that `usage` field can be also nullable(empty)
> Object containing actual usage data for the instance; the value is {} when usage data is unavailable[[1]](https://v3-apidocs.cloudfoundry.org/version/3.111.0/#the-process-stats-object)

Fix parse of ProcessStatisticsResource with nullable fields

---

cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/deployments/_DeploymentRelationships.java

App relationship property can be null on first push.
Fixes #1042

Marks a Deployment Resource's 'app' relationship property as Nullable

---

cloudfoundry-client/src/main/java/org/cloudfoundry/client/CloudFoundryClient.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/deployments/_DeploymentRelationships.java
integration-test/src/test/java/org/cloudfoundry/CloudFoundryVersion.java
integration-test/src/test/java/org/cloudfoundry/client/v3/DeploymentsTest.java

1. Adds support for CC API version 2.171.0
2. Handles the removal of the Deployment Resource's 'state' property - this data is now present in the 'status' property
3. Adds test accounting for # 2

CC API version 2.171.0

---

cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/_DefaultConnectionContext.java
cloudfoundry-client-reactor/src/test/java/org/cloudfoundry/reactor/DefaultConnectionContextTest.java

Previously, if no additional http configuration was set then the default http client configuration would not be applied either. This resulted in settings like the proxy settings and wire tap settings not being applied by default, which is the intention.
Resolves #1143
Signed-off-by: Daniel Mikusa <dmikusa@vmware.com>

Ensure that http client is always configured

---

cloudfoundry-client/src/main/java/org/cloudfoundry/client/CloudFoundryClient.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/builds/Build.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/routes/_Destination.java
integration-test/src/test/java/org/cloudfoundry/CloudFoundryVersion.java

Adds `staging_memory_in_mb` & `staging_disk_in_mb` fields to Build object
Add `protocol` field to Route Destination object
Bump CC API version to `2.180.0`

CC API version bump and necessary changes for support

---

cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/serviceinstances/_GetManagedServiceParametersResponse.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/serviceinstances/_GetUserProvidedCredentialsResponse.java

We hit scenario where service brokers return response including null values and this leads to parsing exception. This is a client limitation and needs to be fixed.

Allow null values in map of service parameters

---

.idea/misc.xml
integration-test/src/test/java/org/cloudfoundry/client/v3/ServiceInstancesTest.java

The `update` test does two things: 1.) it creates a managed service instance and 2.) it updates the managed service instance. The second part was failing because CloudController will refuse to update a service that's still being created.
The update job was calling a method `waitForCompletionOnCreate` which was looking at the CreateServiceInstanceResponse object to see if it had an job id, if it did, then it would call `JobUtils.waitForCompletion(cloudFoundryClient, Duration.ofMinutes(1), createServiceInstanceResponse.getJobId().get())` and then return `getServiceInstanceIdByName(cloudFoundryClient, serviceInstanceName)`. The problem is that the call to `JobUtils.waitForCompletion` was creating a flow but nothing was subscribing to it, so it never actually ran and the test would not pause …

Fixes issue where test was not waiting for the creation of service in stance to complete

---

cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/servicebindings/ServiceBinding.java
cloudfoundry-util/src/main/java/org/cloudfoundry/util/JobUtils.java

The fix related with `waitForCompletion` method is related to state [POLLING ](https://v3-apidocs.cloudfoundry.org/version/3.128.0/#jobs).
Second change is related with ability to use "lastOperation" field from [ServiceBinding](https://github.com/cloudfoundry/cf-java-client/blob/main/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/servicebindings/ServiceBinding.java)

Fix polling of async v3 jobs and make getLastOperation method public

---

ci/tcp-routes.yml
cloudfoundry-client/src/main/java/org/cloudfoundry/client/CloudFoundryClient.java
integration-test/src/test/java/org/cloudfoundry/CloudFoundryVersion.java

- Fixes for integration tests
- CAPI version support

Bump min supported CAPI version, increase default memory quota for tests

---

ci/Dockerfile

Since permissions for `repo.spring.io` have been changed, this PR updates the Dockerfile to use the [DockerHub image](https://hub.docker.com/r/springio/concourse-release-scripts/tags) as the source for `concourse-release-scripts`.
Uses version 0.3.4 for now as 0.4.0 is built with Java 17

Updates Dockerfile with new script source

---

cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/_Relationship.java
cloudfoundry-client/src/test/java/org/cloudfoundry/client/v3/RelationshipTest.java
cloudfoundry-client/src/test/java/org/cloudfoundry/client/v3/domains/ShareDomainRequestTest.java

Makes guid optional in Relationship

---

cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/routes/Route.java
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/routes/_RouteOptions.java

- Introduced in CAPI 3.183 - https://github.com/cloudfoundry/cloud_controller_ng/pull/4080

Add v3.Route.options properties

---

cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/ApplicationLogType.java
cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/Applications.java
cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/DefaultApplications.java
cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/_ApplicationLog.java
cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/_ApplicationLogsRequest.java
integration-test/src/test/java/org/cloudfoundry/operations/ApplicationsTest.java

We should cut a release with what we have now. Once it is out, we can work on merging "recent logs" support for TAS 4.x
This PR paves the way for the work on logcache-based logging.
The DopplerClient does not work with Loggregator >= 107.0.0, and we cannot obtain "recent" logs. Until this is fixed, we cannot cut a release. That is the only blocking test.
- See :
- gh-1181
- gh-1230 
- gh-1237
- Prepare for supporting log-cache in place of the doppler client with the correct deprecation markers.
- Publish `5.13` with what's in main.
- Replace the `Applications#logs` implementation using the logcache client, both `--recent` and streaming logs.
- Publish `6.0` with the new logs implementation, deleting the old doppler-based `#logs` method.

Deprecate doppler-based ApplicationsTests#logs, restrict tests to to CF 2.x line

---

cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/tokenprovider/AbstractUaaTokenProvider.java

If the UAA returns an HTTP 500 on refresh tokens because it is not valid anymore, the refresh token is not invalidated, stays in cache and is never "cleaned up".
This invalidates the refresh token, regardless of the UAA error.
Not planning to merge this for now, but it showcases what changes need to be made.

Recover from all refresh-token related errors by requesting a new token

---

cloudfoundry-client-reactor/src/test/java/org/cloudfoundry/reactor/client/v3/droplets/ReactorDropletsTest.java
cloudfoundry-client-reactor/src/test/resources/fixtures/client/v3/droplets/GET_response.json
cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/droplets/DropletState.java

Add the AWAITING_UPLOAD and PROCESSING_UPLOAD state for the Droplet resource, as stated in the CF API (https://v3-apidocs.cloudfoundry.org/version/3.192.0/#droplets).
Extend the ReactorDropletsTests to test those two new states.

Add the AWAITING_UPLOAD and PROCESSING_UPLOAD state for the Droplet Resource.

---

cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/securitygroups/_ListSecurityGroupsRequest.java
integration-test/src/test/java/org/cloudfoundry/client/v3/SecurityGroupsTest.java

v3._ListSecurityGroupsRequest extends the v2.PaginatedRequest which is incorrect. It needs to extend the v3.PaginatedRequest. The code fixes the incorrect package referenced in v3._ListSecurityGroupsRequest and adds a integration test case
Issue Link: https://github.com/cloudfoundry/cf-java-client/issues/1242

Fixing pagination on v3._ListSecurityGroupsRequest

---

integration-test/src/test/java/org/cloudfoundry/client/v2/BuildpacksTest.java

- The tests were too precise in checking the results. Now that the `lifecycle` property has been introduced in newer CAPI versions, the results are different between CAPI versions.
- We now only check the basic information we care about in those tests (e.g. does the Buildpack exist given its name, or are the updated fields actually updated).

Fix v2.BuildpacksTest for CAPI < 2.209.x

---

integration-test/src/test/java/org/cloudfoundry/IntegrationTestConfiguration.java
integration-test/src/test/java/org/cloudfoundry/client/v2/StacksTest.java
integration-test/src/test/java/org/cloudfoundry/client/v3/BuildpacksTest.java
integration-test/src/test/java/org/cloudfoundry/client/v3/StacksTest.java

We want to run integration tests against TAS 6 and TAS 10.
They run on `cflinuxfs4`, whereas TAS 4 runs on `cflinuxfs3`.
We support both in our integration tests now, and select the most recent `cflinuxfs` version available.

Support multiple stack versions in integration tests.

---

ci/integration-test.sh

Internal CI has moved, and the contract for CI has changed. Update ci script accordingly.

ci: Update APIHOST from CI testbed

---

integration-test/src/test/java/org/cloudfoundry/CleanupCloudFoundryAfterClass.java
integration-test/src/test/java/org/cloudfoundry/CloudFoundryCleaner.java
integration-test/src/test/java/org/cloudfoundry/IntegrationTestConfiguration.java
integration-test/src/test/java/org/cloudfoundry/client/v2/ApplicationsTest.java
integration-test/src/test/java/org/cloudfoundry/client/v2/ServiceBrokersTest.java
integration-test/src/test/java/org/cloudfoundry/client/v3/AdminTest.java
integration-test/src/test/java/org/cloudfoundry/client/v3/ApplicationsTest.java
integration-test/src/test/java/org/cloudfoundry/client/v3/DeploymentsTest.java
integration-test/src/test/java/org/cloudfoundry/client/v3/ProcessesTest.java
integration-test/src/test/java/org/cloudfoundry/client/v3/ServiceBrokersTest.java
integration-test/src/test/java/org/cloudfoundry/client/v3/TasksTest.java
integration-test/src/test/java/org/cloudfoundry/logcache/v1/LogCacheTest.java
integration-test/src/test/java/org/cloudfoundry/operations/ApplicationsTest.java
integration-test/src/test/java/org/cloudfoundry/operations/RoutesTest.java
integration-test/src/test/java/org/cloudfoundry/operations/ServiceAdminTest.java
integration-test/src/test/java/org/cloudfoundry/operations/ServicesTest.java

- A few lifecycle fixes here and there, ensuring the tests have the required dependencies.
- Removed unused SecureRandom bean
- The big chunck of this PR is to fix the "CloudFoundryCleaner" which was only called once. See explanation from the asociated commit:
- CloudFoundryCleaner was not properly triggered on every test. In fact, it was only triggered when the integration test's TestContext would change, which was very infrequent (unsure it was ever triggered). It's possible the cleanup only ever happened when the test suite started.
- This is because the "clean" method was linked to lifecycle methods of the CloudFoundryCleaner bean, which was only created once.
- The solution is to add `@DirtiesContext`, to trigger a re-creation of this bean. We don't want to do it on every test, …

Fix integration test cleanup
